### PR TITLE
Make Juggernaut more responsive

### PR DESCRIPTION
**Pull request by cpunk2140**
I lowered the minimum width window constraint from 1000px to 400px and made the pages responsive. Everything should be functional and look good at small screen sizes, with the exception of the nice visual manage channels page, which, despite being still fully functional, it's aesthetically broken at smaller screen sizes. I'll have to come back later to fix it, sadly, for now, my CSS skills are not good enough to make it look good 😞

### CODE REVIEW

**Comment by cpunk2140** [comment]
@johncantrell97 I added back the progress when connecting to the wallet and added a "Start Conversation" tooltip. The Manage Channels page doesn't look great, but it's functional, so my thought is to merge as it is and come back later to fix it. That would probably be a good place to use the css grid layout?

Review when you can and let me know what you think.

**Comment by johncantrell97** [comment]
@all-contributors please add @cpunk2140 for code and design

**Comment by johncantrell97** [comment]
i think this PR got screwed up somehow between contribution bot and the force pushes?

When I look at it locally I still see all the separate commits and I'm not seeing any kind of loading indicator on launch screen.  When I look at it on github I only see 1 big commit.

Maybe re-open your latest in a new PR?

**Comment by cpunk2140** [comment]
Closed in favour of https://github.com/LN-Juggernaut/juggernaut-desktop/pull/61

**Pull request closed without merging**
