### PR TITLE
implement emoji picker for chat

### PR DESCRIPTION
**Pull request by johncantrell97**
implements https://github.com/LN-Juggernaut/juggernaut-desktop/issues/12

### CODE REVIEW

**Comment by stefan-mihaila** [comment]
Loading seems to take a long time 1st time, and the picker seems broken, but works fine after. Just some minor preference nitpicks, but looks good overall

**Comment by johncantrell97** [comment]
Thanks for the feedback.  I didn't even know about ^⌘Space shortcut O.o on mac. I think they can be rendered native.  Do you mean instead of 'twitter' or instead of as buttons? 

I mostly removed the categories and color picker as I never use them but also because I was seeing lots of strange behavior with the category picker breaking. 

I also noticed the extremely slow 1st load and then fine after.  I'll spend a little more time to see fi I can get those things worked out but don't want to spend too long on emojis :)

**Comment by stefan-mihaila** [comment]
Not sure what does instead of as buttons means.

What I meant is, in the picker, instead of twitter like emoticons, when on a mac, they would look the same as emoticons that I send using ^⌘Space. I would assume that Windows and Linux (Gnome, KDE, Xfce etc) have their own sets. When I tried it, they look like the twitter ones in the picker, but once picked, they look like the mac ones in the chat anyway, so doesn't really make sense to have them look differently in the picker.

Haha, yeah, it's kinda funny to have a serious discussion about how to implement emoticons. btw, ^⌘Space doesn't always work, and it drives me crazy 😡

**Comment by johncantrell97** [comment]
Yes, they have option to render as native in picker, which I changed it to.  I think this also fixes the 1st time lag as I cannot reproduce that after switching to native.  I think it was downloading twitter/apple/etc image set if you are using that which was causing the lag.

I am still having trouble with the category selector though.  It only starts working after clicking on an emoji.  Also noticed the skin tone selector does not change the skin tone for all emojis, only some, is that normal?

**Comment by stefan-mihaila** [comment]
It might fix the lag if it uses unicode and let the OS render them, instead of having small images that replicate the native emoticons. I'm not sure if that's how it does it.

If the category doesn't work correctly, feel free to drop it. As you said, we don't want to spend too much working on this.

Yeah, it's normal that not all emoticons have skin color. You can check by comparing them with the Apple ones in ^⌘Space (or go to Edit in the menu bar you'll find Emoji & Symbols there) There's a standard way to represent them in Unicode, altering for the color, and not all of them implement that.

**Comment by johncantrell97** [comment]
Yeah, I compared with how Slack does it and noticed same behavior there.  Going to spend another 15 mins on the categories and drop it for now if I can't get it working.  Will open a separate issue to add back in and fix category picker.

**Comment by johncantrell97** [comment]
@all-contributors please add @johncantrell97 for code

**Pull request merged**
